# Week 2 — Python, NumPy & Pandas

### A crash course for the NLP course

This notebook is a **general** refresher on the three tools you will use all semester.
There is **no NLP here** — just the Python, NumPy and Pandas you need before Week 3.

**How to use it:** read each section, run every code cell (Shift+Enter), then do the
*Your turn* exercise before moving on. Solutions are at the very end.

**Contents**
1. Python core — variables, types, control flow
2. Python collections — list, tuple, dict, set
3. Functions, comprehensions, and a little file I/O
4. NumPy — arrays, vectorisation, broadcasting
5. Pandas — Series, DataFrame, selection, grouping
6. Putting it together — a tiny data workflow
7. Exercises (solutions at the end)

> Environment check: run the next cell first. If it errors, your environment is not ready —
> revisit the Week 2 setup steps.

In [ ]:
import sys
import numpy as np
import pandas as pd

print("Python :", sys.version.split()[0])
print("NumPy  :", np.__version__)
print("Pandas :", pd.__version__)
print("All three imported successfully.")

Python : 3.12.3
NumPy  : 2.4.4
Pandas : 3.0.2
All three imported successfully.


## 1. Python core

### Variables and dynamic typing

Python has no type declarations. A variable is just a name bound to a value, and the
same name can later point to a different type. Use `type()` to inspect.

In [ ]:
n = 42            # int
pi = 3.14159      # float
name = "Ada"      # str
is_ready = True   # bool
nothing = None    # the absence of a value

for v in (n, pi, name, is_ready, nothing):
    print(f"{str(v):8}  ->  {type(v).__name__}")

42        ->  int
3.14159   ->  float
Ada       ->  str
True      ->  bool
None      ->  NoneType


### Numbers and arithmetic

Note the two division operators: `/` always gives a float, `//` floors to an integer,
and `%` is the remainder. `**` is exponentiation.

In [ ]:
a, b = 17, 5
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)     # true division -> float
print("a // b =", a // b)    # floor division -> int
print("a % b  =", a % b)     # remainder
print("a ** b =", a ** b)    # 17 to the power 5

a + b  = 22
a - b  = 12
a * b  = 85
a / b  = 3.4
a // b = 3
a % b  = 2
a ** b = 1419857


### Strings

Strings are immutable sequences of characters. f-strings (the `f"..."` form) are the
modern way to build text from values. A few everyday methods are shown below.

In [ ]:
s = "  Hello, World  "
print(repr(s.strip()))          # remove surrounding whitespace
print(s.strip().lower())        # lowercase
print(s.strip().upper())        # uppercase
print(s.strip().replace("World", "Python"))
print(s.strip().split(","))     # split into a list on a delimiter
print("-".join(["a", "b", "c"]))  # join a list into a string

# f-strings: embed expressions directly
qty, price = 3, 4.5
print(f"{qty} items cost {qty * price:.2f} dollars")

'Hello, World'
hello, world
HELLO, WORLD
Hello, Python
['Hello', ' World']
a-b-c
3 items cost 13.50 dollars


### Control flow: if / elif / else

Python uses **indentation** (four spaces) to define blocks — there are no braces.
Comparison operators return booleans, and you combine them with `and`, `or`, `not`.

In [ ]:
score = 73

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
else:
    grade = "F"

print(f"Score {score} -> grade {grade}")
print("Passed" if score >= 60 else "Failed")   # ternary expression

Score 73 -> grade C
Passed


### Loops: for and while

`for` iterates over any sequence. `range(start, stop, step)` generates integers (the
`stop` value is excluded). `enumerate` gives you the index alongside the value.

In [ ]:
# sum the even numbers from 0 to 9
total = 0
for i in range(10):
    if i % 2 == 0:
        total += i
print("sum of evens 0..9:", total)

# enumerate: index + value together
for idx, letter in enumerate(["x", "y", "z"]):
    print(idx, letter)

# while loop
countdown = 3
while countdown > 0:
    print("tick", countdown)
    countdown -= 1

sum of evens 0..9: 20
0 x
1 y
2 z
tick 3
tick 2
tick 1


> **Your turn (1).** Write a loop that prints every number from 1 to 20, but prints
> `"fizz"` instead when the number is divisible by 3. (Solution at the end.)

## 2. Python collections

Four built-in container types cover almost everything:

| Type    | Syntax         | Ordered | Mutable | Duplicates | Typical use |
|---------|----------------|---------|---------|------------|-------------|
| `list`  | `[1, 2, 3]`    | yes     | yes     | yes        | a sequence you will change |
| `tuple` | `(1, 2, 3)`    | yes     | **no**  | yes        | a fixed record |
| `dict`  | `{"a": 1}`     | yes*    | yes     | keys unique| lookup by key |
| `set`   | `{1, 2, 3}`    | no      | yes     | **no**     | membership / dedup |

\* dicts preserve insertion order in modern Python.

### Lists — the workhorse

Indexing is zero-based. Negative indices count from the end. Slicing `a[start:stop]`
returns a sub-list (stop excluded).

In [ ]:
nums = [10, 20, 30, 40, 50]
print("first :", nums[0])
print("last  :", nums[-1])
print("slice :", nums[1:4])      # indices 1,2,3
print("every other:", nums[::2])

nums.append(60)                  # add to end
nums.insert(0, 5)                # insert at position
nums.remove(30)                  # remove first matching value
popped = nums.pop()              # remove & return last
print("after edits:", nums, "| popped:", popped)
print("length:", len(nums), "| max:", max(nums), "| sum:", sum(nums))

first : 10
last  : 50
slice : [20, 30, 40]
every other: [10, 30, 50]
after edits: [5, 10, 20, 40, 50] | popped: 60
length: 5 | max: 50 | sum: 125


### Tuples — fixed records

A tuple cannot be changed after creation, which makes it a good lightweight record.
You can unpack a tuple straight into variables.

In [ ]:
point = (3, 4)
x, y = point                     # tuple unpacking
print(f"x={x}, y={y}")

# functions often return tuples
def min_max(values):
    return min(values), max(values)

lo, hi = min_max([7, 2, 9, 4])
print("lo:", lo, "| hi:", hi)

x=3, y=4
lo: 2 | hi: 9


### Dicts — lookup by key

A dict maps keys to values. Access with `d[key]`, but prefer `d.get(key, default)`
when a key might be missing, to avoid a `KeyError`.

In [ ]:
ages = {"Ada": 36, "Alan": 41, "Grace": 45}

print("Ada's age:", ages["Ada"])
print("Unknown  :", ages.get("Bob", "not found"))

ages["Bob"] = 29                 # add / update
del ages["Alan"]                 # remove

for name, age in ages.items():   # iterate key+value
    print(f"{name:6} -> {age}")

print("keys  :", list(ages.keys()))
print("values:", list(ages.values()))

Ada's age: 36
Unknown  : not found
Ada    -> 36
Grace  -> 45
Bob    -> 29
keys  : ['Ada', 'Grace', 'Bob']
values: [36, 45, 29]


### Sets — uniqueness and membership

A set stores unique elements and tests membership very fast. Great for removing
duplicates and for set algebra (union, intersection, difference).

In [ ]:
a = {1, 2, 3, 4}
b = {3, 4, 5, 6}

print("union       :", a | b)
print("intersection:", a & b)
print("difference  :", a - b)
print("3 in a?     :", 3 in a)

# deduplicate a list by passing it through a set
dupes = [1, 1, 2, 3, 3, 3, 4]
print("unique:", sorted(set(dupes)))

union       : {1, 2, 3, 4, 5, 6}
intersection: {3, 4}
difference  : {1, 2}
3 in a?     : True
unique: [1, 2, 3, 4]


> **Your turn (2).** Given `prices = [4, 9, 4, 2, 9, 7, 2]`, use a set to find how
> many *distinct* prices there are, then use a dict to count how many times each price
> appears. (Solution at the end.)

## 3. Functions, comprehensions, and file I/O

### Defining functions

Functions can have default arguments and should have a docstring. The `return`
statement hands a value back; without it a function returns `None`.

In [ ]:
def greet(name, greeting="Hello"):
    """Return a greeting string."""
    return f"{greeting}, {name}!"

print(greet("Ada"))
print(greet("Alan", greeting="Hi"))

def stats(values):
    """Return the count, total and mean of a list of numbers."""
    n = len(values)
    total = sum(values)
    return n, total, total / n

print(stats([2, 4, 6, 8]))

Hello, Ada!
Hi, Alan!
(4, 20, 5.0)


### Lambdas and higher-order functions

A `lambda` is a small anonymous function. Functions like `sorted`, `map` and `filter`
take other functions as arguments.

In [ ]:
square = lambda x: x * x
print("square(5):", square(5))

# sort by a key function
words = ["banana", "fig", "cherry", "kiwi"]
print("by length:", sorted(words, key=len))

# map applies a function to every element; list() to materialise
print("squares:", list(map(lambda x: x ** 2, [1, 2, 3, 4])))

# filter keeps elements where the function is True
print("evens  :", list(filter(lambda x: x % 2 == 0, range(10))))

square(5): 25
by length: ['fig', 'kiwi', 'banana', 'cherry']
squares: [1, 4, 9, 16]
evens  : [0, 2, 4, 6, 8]


### Comprehensions — the Pythonic loop

A list comprehension builds a list in one expressive line. There are dict and set
comprehensions too. Prefer these over manual `append` loops when they stay readable.

In [ ]:
# list comprehension: squares of 0..9
squares = [x ** 2 for x in range(10)]
print(squares)

# with a condition
evens = [x for x in range(20) if x % 2 == 0]
print(evens)

# dict comprehension: number -> its square
sq_map = {x: x ** 2 for x in range(1, 6)}
print(sq_map)

# set comprehension: distinct remainders mod 3
print({x % 3 for x in range(10)})

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{0, 1, 2}


### A little file I/O

The `with` statement opens a file and closes it automatically. We write a small text
file and read it back. (This is general file handling — nothing NLP-specific.)

In [ ]:
# write three lines
with open("demo.txt", "w") as f:
    for i in range(1, 4):
        f.write(f"line {i}\n")

# read it all back
with open("demo.txt") as f:
    content = f.read()
print("full contents:")
print(content)

# read line by line into a list, stripping newlines
with open("demo.txt") as f:
    lines = [line.strip() for line in f]
print("as list:", lines)

full contents:
line 1
line 2
line 3

as list: ['line 1', 'line 2', 'line 3']


> **Your turn (3).** Write a function `word_lengths(words)` that takes a list of
> strings and returns a dict mapping each word to its length, using a dict
> comprehension. (Solution at the end.)

## 4. NumPy — numerical arrays

NumPy's core object is the **ndarray**: a grid of numbers of one type. The reason to
use it over plain lists is **vectorisation** — operations apply to the whole array at
C speed, with no Python loop.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("array   :", arr)
print("dtype   :", arr.dtype)     # data type of the elements
print("shape   :", arr.shape)     # dimensions
print("ndim    :", arr.ndim)      # number of axes
print("size    :", arr.size)      # total elements

array   : [1 2 3 4 5]
dtype   : int64
shape   : (5,)
ndim    : 1
size    : 5


### Creating arrays

Common constructors. `arange` is like `range`; `linspace` gives evenly spaced points;
`zeros`/`ones` fill a shape; `reshape` changes the shape without copying data.

In [ ]:
print("arange   :", np.arange(0, 10, 2))
print("linspace :", np.linspace(0, 1, 5))   # 5 points from 0 to 1 inclusive
print("zeros    :", np.zeros(4))
print("ones 2x3 :\n", np.ones((2, 3)))

m = np.arange(12).reshape(3, 4)              # 3 rows, 4 cols
print("reshaped 3x4:\n", m)

arange   : [0 2 4 6 8]
linspace : [0.   0.25 0.5  0.75 1.  ]
zeros    : [0. 0. 0. 0.]
ones 2x3 :
 [[1. 1. 1.]
 [1. 1. 1.]]
reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Vectorised arithmetic

Arithmetic on arrays is element-wise and needs no loop. This is both shorter and much
faster than iterating.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b :", a + b)
print("a * b :", a * b)
print("a ** 2:", a ** 2)
print("b / a :", b / a)
print("a > 2 :", a > 2)           # element-wise comparison -> bool array

# a scalar applies to every element
print("a * 100:", a * 100)

a + b : [11 22 33 44]
a * b : [ 10  40  90 160]
a ** 2: [ 1  4  9 16]
b / a : [10. 10. 10. 10.]
a > 2 : [False False  True  True]
a * 100: [100 200 300 400]


### Aggregations and axes

Reductions like `sum`, `mean`, `max` collapse an array to a summary. On a 2-D array,
`axis=0` works **down the columns** and `axis=1` works **across the rows**.

In [ ]:
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("total sum   :", data.sum())
print("mean        :", data.mean())
print("max         :", data.max())
print("std dev     :", round(float(data.std()), 4))
print("col sums (axis=0):", data.sum(axis=0))   # one value per column
print("row sums (axis=1):", data.sum(axis=1))   # one value per row

total sum   : 21
mean        : 3.5
max         : 6
std dev     : 1.7078
col sums (axis=0): [5 7 9]
row sums (axis=1): [ 6 15]


### Indexing, slicing, and boolean masks

2-D indexing is `arr[row, col]`. Slicing works per axis. A **boolean mask** selects
elements where a condition is True — this is one of NumPy's most useful features.

In [ ]:
m = np.arange(1, 13).reshape(3, 4)
print("matrix:\n", m)
print("element [1,2]:", m[1, 2])
print("row 0       :", m[0])
print("column 1    :", m[:, 1])
print("top-left 2x2:\n", m[:2, :2])

# boolean masking
flat = np.array([5, 12, 7, 20, 3, 15])
mask = flat > 10
print("mask      :", mask)
print("values>10 :", flat[mask])
flat[flat < 10] = 0               # assign through a mask
print("zeroed    :", flat)

matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
element [1,2]: 7
row 0       : [1 2 3 4]
column 1    : [ 2  6 10]
top-left 2x2:
 [[1 2]
 [5 6]]
mask      : [False  True False  True False  True]
values>10 : [12 20 15]
zeroed    : [ 0 12  0 20  0 15]


### Broadcasting

Broadcasting lets arrays of different shapes combine when their shapes are compatible.
The smaller array is "stretched" across the larger one without copying. Here we add a
row vector to every row of a matrix.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row = np.array([10, 20, 30])

print("matrix + row (broadcast):\n", matrix + row)

# centre each column by subtracting its mean
centered = matrix - matrix.mean(axis=0)
print("column-centered:\n", centered)
print("new column means:", centered.mean(axis=0))

matrix + row (broadcast):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
column-centered:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
new column means: [0. 0. 0.]


> **Your turn (4).** Create the array `np.arange(1, 21)`, then use a boolean mask to
> keep only the values divisible by 3, and print their mean. (Solution at the end.)

## 5. Pandas — labelled tables

Pandas adds two objects on top of NumPy:

- **Series** — a 1-D labelled array (like one column).
- **DataFrame** — a 2-D labelled table (rows + named columns), the object you will use most.

In [ ]:
s = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])
print(s)
print()
print("value at 'c':", s["c"])
print("mean        :", s.mean())

a    10
b    20
c    30
d    40
dtype: int64

value at 'c': 30
mean        : 25.0


### Building a DataFrame

The most common way is from a dict of columns. Each key is a column name, each value a
list of that column's data.

In [ ]:
df = pd.DataFrame({
    "name":    ["Ada", "Alan", "Grace", "Linus", "Katherine"],
    "dept":    ["Math", "CS", "CS", "CS", "Math"],
    "age":     [36, 41, 45, 33, 52],
    "salary":  [85, 92, 78, 88, 95],
})
df

        name  dept  age  salary
0        Ada  Math   36      85
1       Alan    CS   41      92
2      Grace    CS   45      78
3      Linus    CS   33      88
4  Katherine  Math   52      95

### Inspecting a DataFrame

The first things you do with any new table: look at the top rows, the shape, the column
types, and summary statistics.

In [ ]:
print("shape:", df.shape)
print("\ncolumns:", list(df.columns))
print("\ndtypes:")
print(df.dtypes)

shape: (5, 4)

columns: ['name', 'dept', 'age', 'salary']

dtypes:
name        str
dept        str
age       int64
salary    int64
dtype: object


In [ ]:
df.describe()    # summary stats for numeric columns

             age     salary
count   5.000000   5.000000
mean   41.400000  87.600000
std     7.503333   6.580274
min    33.000000  78.000000
25%    36.000000  85.000000
50%    41.000000  88.000000
75%    45.000000  92.000000
max    52.000000  95.000000

### Selecting columns and rows

Pick a single column with `df["col"]` (a Series) or several with `df[["c1","c2"]]`
(a DataFrame). Select rows by **label** with `.loc` and by **integer position** with
`.iloc`.

In [ ]:
print("one column (age):")
print(df["age"].tolist())

print("\ntwo columns:")
print(df[["name", "salary"]])

one column (age):
[36, 41, 45, 33, 52]

two columns:
        name  salary
0        Ada      85
1       Alan      92
2      Grace      78
3      Linus      88
4  Katherine      95


In [ ]:
print("row at position 0 (.iloc):")
print(df.iloc[0])

print("\nrows 1..2, columns name+age (.loc):")
print(df.loc[1:2, ["name", "age"]])

row at position 0 (.iloc):
name       Ada
dept      Math
age         36
salary      85
Name: 0, dtype: object

rows 1..2, columns name+age (.loc):
    name  age
1   Alan   41
2  Grace   45


### Boolean filtering

Just like NumPy masks: build a condition on a column, then index the DataFrame with it.
Combine conditions with `&` (and) / `|` (or), wrapping each in parentheses.

In [ ]:
print("CS staff only:")
print(df[df["dept"] == "CS"])

print("\nolder than 40 AND salary > 80:")
print(df[(df["age"] > 40) & (df["salary"] > 80)])

CS staff only:
    name dept  age  salary
1   Alan   CS   41      92
2  Grace   CS   45      78
3  Linus   CS   33      88

older than 40 AND salary > 80:
        name  dept  age  salary
1       Alan    CS   41      92
4  Katherine  Math   52      95


### Adding and transforming columns

A new column is just an assignment. Operations are vectorised, exactly like NumPy.

In [ ]:
df["salary_k"] = df["salary"] * 1000        # vectorised
df["senior"]   = df["age"] >= 45             # boolean column
df

        name  dept  age  salary  salary_k  senior
0        Ada  Math   36      85     85000   False
1       Alan    CS   41      92     92000   False
2      Grace    CS   45      78     78000    True
3      Linus    CS   33      88     88000   False
4  Katherine  Math   52      95     95000    True

### Grouping and aggregation

`groupby` splits the table by a column's values, then you apply an aggregation to each
group. This is the single most useful Pandas operation for summarising data.

In [ ]:
# average age and salary per department
print(df.groupby("dept")[["age", "salary"]].mean())

print("\nheadcount per department:")
print(df.groupby("dept").size())

            age  salary
dept                   
CS    39.666667    86.0
Math  44.000000    90.0

headcount per department:
dept
CS      3
Math    2
dtype: int64


### Sorting and a couple of handy methods

In [ ]:
print("sorted by age (desc):")
print(df.sort_values("age", ascending=False)[["name", "age"]])

print("\nunique departments:", df["dept"].unique().tolist())
print("value counts:")
print(df["dept"].value_counts())

sorted by age (desc):
        name  age
4  Katherine   52
2      Grace   45
1       Alan   41
0        Ada   36
3      Linus   33

unique departments: ['Math', 'CS']
value counts:
dept
CS      3
Math    2
Name: count, dtype: int64


> **Your turn (5).** From `df`, select everyone in the `Math` department, then print
> their mean salary. (Solution at the end.)

## 6. Putting it together — a tiny workflow

A realistic mini-task touching all three tools: generate some numbers with NumPy, load
them into a Pandas DataFrame, clean and summarise. (Still no NLP — just data.)

In [ ]:
# 1. make reproducible fake data with NumPy
rng = np.random.default_rng(seed=0)      # seeded generator -> reproducible
scores = rng.integers(40, 100, size=12)  # 12 exam scores
groups = rng.choice(["A", "B", "C"], size=12)

# 2. load into a DataFrame
exam = pd.DataFrame({"group": groups, "score": scores})
print("raw data:")
print(exam)

raw data:
   group  score
0      B     91
1      B     78
2      C     70
3      C     56
4      B     58
5      B     42
6      B     44
7      C     40
8      A     50
9      C     88
10     C     78
11     A     94


In [ ]:
# 3. add a pass/fail column (vectorised), then summarise per group
exam["passed"] = exam["score"] >= 60

summary = exam.groupby("group").agg(
    n=("score", "size"),
    mean_score=("score", "mean"),
    pass_rate=("passed", "mean"),
)
print("summary per group:")
print(summary.round(2))

summary per group:
       n  mean_score  pass_rate
group                          
A      2        72.0        0.5
B      5        62.6        0.4
C      5        66.4        0.6


In [ ]:
# 4. a NumPy sanity check on the same numbers
arr = exam["score"].to_numpy()           # DataFrame column -> NumPy array
print("overall mean :", round(arr.mean(), 2))
print("overall std  :", round(arr.std(), 2))
print("min / max    :", arr.min(), "/", arr.max())
print("how many >=60:", int((arr >= 60).sum()), "of", arr.size)

overall mean : 65.75
overall std  : 19.04
min / max    : 40 / 94
how many >=60: 6 of 12


## 7. Exercises

Try these before looking at the solutions in the final cell. They only use what is in
this notebook.

1. **Temperatures.** Given `temps_c = [0, 20, 37, 100]` (Celsius), build a new list of
   the same values in Fahrenheit using a list comprehension. Formula: `F = C * 9/5 + 32`.

2. **Word counter.** Given `items = ["pen","book","pen","pen","book","ruler"]`, build a
   dict mapping each item to how many times it appears. (No `collections` import.)

3. **NumPy normalise.** Create `x = np.array([2, 4, 6, 8, 10])`. Produce a new array that
   is `x` scaled to the range 0–1 (subtract the min, divide by the range).

4. **Pandas filter + group.** Using the `df` from section 5, compute the average `salary`
   for staff aged under 45, grouped by `dept`.

5. **Challenge.** Write a function `summarise(numbers)` that returns a dict with keys
   `min`, `max`, `mean`, `count`, computed with NumPy, and test it on `[3, 1, 4, 1, 5, 9]`.

In [ ]:
# ---------------------------------------------------------------
# SOLUTIONS  (try the exercises yourself first)
# ---------------------------------------------------------------

# --- Your turn (1): fizz ---
print("Your turn 1:")
for i in range(1, 21):
    print("fizz" if i % 3 == 0 else i, end=" ")
print("\n")

# --- Your turn (2): distinct prices + counts ---
prices = [4, 9, 4, 2, 9, 7, 2]
print("Your turn 2:")
print("  distinct:", len(set(prices)))
counts = {}
for p in prices:
    counts[p] = counts.get(p, 0) + 1
print("  counts  :", counts, "\n")

# --- Your turn (3): word_lengths ---
def word_lengths(words):
    return {w: len(w) for w in words}
print("Your turn 3:", word_lengths(["a", "bb", "ccc"]), "\n")

# --- Your turn (4): divisible by 3, mean ---
v = np.arange(1, 21)
div3 = v[v % 3 == 0]
print("Your turn 4: values", div3, "mean", div3.mean(), "\n")

# --- Your turn (5): Math dept mean salary ---
print("Your turn 5: Math mean salary =",
      df[df["dept"] == "Math"]["salary"].mean(), "\n")

# --- Exercise 1: C -> F ---
temps_c = [0, 20, 37, 100]
temps_f = [c * 9/5 + 32 for c in temps_c]
print("Ex 1:", temps_f)

# --- Exercise 2: item counter ---
items = ["pen", "book", "pen", "pen", "book", "ruler"]
item_counts = {}
for it in items:
    item_counts[it] = item_counts.get(it, 0) + 1
print("Ex 2:", item_counts)

# --- Exercise 3: normalise to 0..1 ---
x = np.array([2, 4, 6, 8, 10])
norm = (x - x.min()) / (x.max() - x.min())
print("Ex 3:", norm)

# --- Exercise 4: under-45 mean salary by dept ---
print("Ex 4:")
print(df[df["age"] < 45].groupby("dept")["salary"].mean())

# --- Exercise 5: summarise ---
def summarise(numbers):
    a = np.array(numbers)
    return {"min": int(a.min()), "max": int(a.max()),
            "mean": float(a.mean()), "count": int(a.size)}
print("Ex 5:", summarise([3, 1, 4, 1, 5, 9]))

Your turn 1:
1 2 fizz 4 5 fizz 7 8 fizz 10 11 fizz 13 14 fizz 16 17 fizz 19 20 

Your turn 2:
  distinct: 4
  counts  : {4: 2, 9: 2, 2: 2, 7: 1} 

Your turn 3: {'a': 1, 'bb': 2, 'ccc': 3} 

Your turn 4: values [ 3  6  9 12 15 18] mean 10.5 

Your turn 5: Math mean salary = 90.0 

Ex 1: [32.0, 68.0, 98.6, 212.0]
Ex 2: {'pen': 3, 'book': 2, 'ruler': 1}
Ex 3: [0.   0.25 0.5  0.75 1.  ]
Ex 4:
dept
CS      90.0
Math    85.0
Name: salary, dtype: float64
Ex 5: {'min': 1, 'max': 9, 'mean': 3.8333333333333335, 'count': 6}


---

### Where this goes next

You now have the three tools the rest of the course relies on:

- **Python** for everything — control flow, collections, functions.
- **NumPy** for fast numerical arrays — the foundation under every model.
- **Pandas** for labelled tables — loading, cleaning and summarising data.

**Week 3** begins the NLP content proper (tokenization). Keep this notebook as a
reference; when a later notebook does `import numpy as np` or builds a DataFrame, the
mechanics are all here.

*Tip:* re-run this whole notebook top to bottom once (Kernel → Restart & Run All). If
every cell runs without error, your environment is ready for the semester.